version: '3'

services:
  rr17:
    image: rr17
    build: .
    command: rails server -p 3000 -b '0.0.0.0'    
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links: 
      - postgres
  postgres:
    image: postgres:9.5
    ports: 
      - "5432:5432"
  mongo:
    image: mongo
    ports:
      - "27017:27017" 