# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28f0c5ba490ec63b2018658677d215afc1359017eb3a94b89b7789476605f57bbc1468185a5c445933c1bc45aa72628616d405f28096551369352fc944b8bcf1

test:
  secret_key_base: 4bee9a919c3fb0b3134b7e75ef13ad3582ec2603eb366a8a4db313a09fc95d4cf0333a04b4a19944a0d3439e817bca78a0cd35fb21161bbb5acc3c6218b3b43c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
